AllCops:
  NewCops: enable
  Exclude:
    - 'vendor/**/*'
    - 'spec/fixtures/**/*'
    - 'tmp/**/*'
    - '.git/**/*'
    - 'bin/*'
  TargetRubyVersion: 2.5
Metrics/BlockLength:
  Max: 500
Metrics/ClassLength:
  Max: 250
Metrics/ModuleLength:
  Max: 250
Metrics/MethodLength:
  Max: 20
Metrics/ParameterLists:
  Max: 6
Layout/ExtraSpacing:
  ForceEqualSignAlignment: true
Layout/LineLength:
  Max: 130
Style/IfUnlessModifier:
  Enabled: false
Style/Lambda:
  Enabled: false
Style/NestedParenthesizedCalls:
  Enabled: false
Style/ClassVars:
  Enabled: false
